Do not attempt key conversions when testing against Chrome on Android.
Original issue's description:
> If you run ChromeDriver on a headless Linux host (no X or Xvfb) and attempt to "sendKeys" to an attached Android device, ChromeDriver dies with:
> org.openqa.selenium.WebDriverException: unknown error: an X display is required for keycode conversions, consider using Xvfb

The Linux host is only used to automate Android devices, so (IMHO) there's no reason ChromeDriver should use the local host's keymap for the *remote* Android device.  Instead, it should only fail if Chrome is running on the *local* host.